In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
from patsy import dmatrices
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
%matplotlib inline

df = pd.read_csv('house_prices.csv')
df.head()

   house_id neighborhood  area  bedrooms  bathrooms      style    price
0      1112            B  1188         3          2      ranch   598291
1       491            B  3512         5          3  victorian  1744259
2      5952            B  1134         3          2      ranch   571669
3      3525            A  1940         4          2      ranch   493675
4      5108            B  2208         6          4  victorian  1101539

In [2]:
df['bedrooms_squared'] = df['bedrooms']*df['bedrooms']

In [3]:
df.head()

,house_id,neighborhood,area,bedrooms,bathrooms,style,price,bedrooms_squared
0,1112,B,1188,3,2,ranch,598291,9
1,491,B,3512,5,3,victorian,1744259,25
2,5952,B,1134,3,2,ranch,571669,9
3,3525,A,1940,4,2,ranch,493675,16
4,5108,B,2208,6,4,victorian,1101539,36

In [4]:
df['intercept'] = 1
lm = sm.OLS(df['price'], df[['intercept','bedrooms', 'bedrooms_squared']])
results = lm.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.582
Model:                            OLS   Adj. R-squared:                  0.582
Method:                 Least Squares   F-statistic:                     4199.
Date:                Sun, 14 Oct 2018   Prob (F-statistic):               0.00
Time:                        12:28:16   Log-Likelihood:                -85302.
No. Observations:                6028   AIC:                         1.706e+05
Df Residuals:                    6025   BIC:                         1.706e+05
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
intercept         1.509e+05   1.58e+04      9.524      0.000     1.2e+05    1.82e+05
bedrooms          5.223e+04   8906.834      5.865      0.000    3.48e+04    6.97e+04
bedrooms_squared  2.446e+04   1184.538     20.647      0.000    2.21e+04    2.68e+04
==============================================================================
Omnibus:                      626.860   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              916.588
Skew:                           0.793   Prob(JB):                    9.23e-200
Kurtosis:                       4.064   Cond. No.                         87.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [5]:
df['area_bed'] = df['area'] * df['bedrooms']

In [6]:
df['intercept'] = 1
lm = sm.OLS(df['price'], df[['intercept', 'area', 'bedrooms', 'area_bed']])
results = lm.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.678
Model:                            OLS   Adj. R-squared:                  0.678
Method:                 Least Squares   F-statistic:                     4232.
Date:                Sun, 14 Oct 2018   Prob (F-statistic):               0.00
Time:                        12:32:05   Log-Likelihood:                -84516.
No. Observations:                6028   AIC:                         1.690e+05
Df Residuals:                    6024   BIC:                         1.691e+05
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept   2.641e+04   1.46e+04      1.813      0.070   -2141.237     5.5e+04
area         327.2817     13.517     24.213      0.000     300.784     353.779
bedrooms    -656.0066   5367.740     -0.122      0.903   -1.12e+04    9866.684
area_bed       3.1373      1.878      1.671      0.095      -0.544       6.818
==============================================================================
Omnibus:                      372.681   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              339.141
Skew:                           0.518   Prob(JB):                     2.27e-74
Kurtosis:                       2.474   Cond. No.                     5.26e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.26e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""